### ISSUE TITLE
Wrong log message

### ISSUE THREAD

**Issue by brunoalvesdefaria** [MGHComputationalPathology/dicom-microscopy-viewer#38]
https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/blob/48dfb9f9d0475a3a850dc3ad215bca5189a8894f/src/api.js#L1035

I think the message here shall be `remove ROI ${uid}`.

**Comment by hackermd** [comment]
Good catch @brunoalvesdefaria. Thanks for reporting.
