### ISSUE TITLE
Offset issue / TotalPixelMatrixOriginSequence is different per layer

### ISSUE THREAD

**Issue by igoroctaviano** [MGHComputationalPathology/dicom-microscopy-viewer#44]
- Original issue: https://github.com/GoogleCloudPlatform/wsi-to-dicom-converter/issues/38

To summarise, the method [coordinateFormatGeometry2Scoord](https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/blob/00c42dd849fcdcc53524b04213280254141c5507/src/viewer.js#L311) was only considering the top-level [TotalPixelMatrixOriginSequence](https://dicom.innolitics.com/ciods/vl-whole-slide-microscopy-image/whole-slide-microscopy-image/00480008) attribute even if it was absent. 

There is a case where a study didn't have this top-level attribute causing the viewer to break when attempting to add new ROIs. Although this attribute did exist nested inside the sequences. 

- I have updated the metadata provider to get the highest [TotalPixelMatrixOriginSequence](https://dicom.innolitics.com/ciods/vl-whole-slide-microscopy-image/whole-slide-microscopy-image/00480008) attribute among the sequences (under [PerFrameFunctionalGroupsSequence](https://dicom.innolitics.com/ciods/multi-frame-grayscale-byte-sc-image/multi-frame-grayscale-byte-sc-image-multi-frame-functional-groups/52009230)) and assign it at the top level of the pyramid metadata to work as an approximation. With that, at least the viewer stopped breaking and I can add the annotations in certain places. The problem now is that the calculation is probably not correct, looks like there is a gap/offset between the image and the overlay causing the coordinates of the annotation to be negative in a small percentage of the viewer's (top).

- @hackermd if [TotalPixelMatrixOriginSequence](https://dicom.innolitics.com/ciods/vl-whole-slide-microscopy-image/whole-slide-microscopy-image/00480008) is absent (at the top level of the pyramid metadata), how can we calculate it based on the nested sequence values? 
- Do we have to update [here](https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/blob/00c42dd849fcdcc53524b04213280254141c5507/src/metadata.js#L43) to consider the offsets under [PerFrameFunctionalGroupsSequence](https://dicom.innolitics.com/ciods/multi-frame-grayscale-byte-sc-image/multi-frame-grayscale-byte-sc-image-multi-frame-functional-groups/52009230)?

**Comment by hackermd** [comment]
>  if TotalPixelMatrixOriginSequence is absent (at the top level of the pyramid metadata), how can we calculate it based on the nested sequence values?

This attribute is type 1 (required) for a good reason. I don't think we can compute the image position (offset in slide coordinate system) from other metadata. We could try of course to register the images, but I would consider this beyond the scope of the viewer.

> Do we have to update here to consider the offsets under PerFrameFunctionalGroupsSequence?

If the `PerFrameFunctionalGroupsSequence` attribute exists, you could construct `TotalPixelMatrixOriginSequence` using the values of `XOffsetInSlideCoordinateSystem` and `XOffsetInSlideCoordinateSystem` for the frame item (see [Plane Position (Slide) Macro](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.12.6.html#table_C.8.12.6.1-1)) that represents the top-left tile in the tiled Total Pixel Matrix.

**Comment by igoroctaviano** [comment]
> > if TotalPixelMatrixOriginSequence is absent (at the top level of the pyramid metadata), how can we calculate it based on the nested sequence values?
> 
> This attribute is type 1 (required) for a good reason. I don't think we can compute the image position (offset in slide coordinate system) from other metadata. We could try of course to register the images, but I would consider this beyond the scope of the viewer.
> 
> > Do we have to update here to consider the offsets under PerFrameFunctionalGroupsSequence?
> 
> If the `PerFrameFunctionalGroupsSequence` attribute exists, you could construct `TotalPixelMatrixOriginSequence` using the values of `XOffsetInSlideCoordinateSystem` and `XOffsetInSlideCoordinateSystem` for the frame item (see [Plane Position (Slide) Macro](http://dicom.nema.org/medical/dicom/current/output/chtml/part03/sect_C.8.12.6.html#table_C.8.12.6.1-1)) that represents the top-left tile in the tiled Total Pixel Matrix.

@hackermd I tried getting the highest XOffsetInSlideCoordinateSystem and XOffsetInSlideCoordinateSystem offsets among the PlanePositionSlideSequence present in the dataset and i was assigning this highest pair to the missing TotalPixelMatrixOriginSequence.

Something like: 
```
function formatMetadata(metadata) {
  let origin = {
    XOffsetInSlideCoordinateSystem: 0,
    YOffsetInSlideCoordinateSystem: 0
  };

  const loadJSONDataset = (elements) => {
    const dataset = {};
    Object.keys(elements).forEach(tag => {
      const keyword = tagToKeyword[tag];
      const vr = elements[tag]['vr'];
      const value = parseFloat(elements[tag]['Value']);

      if (keyword === 'XOffsetInSlideCoordinateSystem') {
        if (value > origin.XOffsetInSlideCoordinateSystem) {
          origin.XOffsetInSlideCoordinateSystem = value;
        }
      }
      
      .... and then ...
      
        const isTiledSparse = dataset.DimensionOrganizationType === 'TILED_SPARSE';
        if (isTiledSparse && !dataset.TotalPixelMatrixOriginSequence) {
          dataset.TotalPixelMatrixOriginSequence = [origin];
        }
```

Debugging with a test data that had the top level TotalPixelMatrixOriginSequence present,  I could get the same value. But using a test data without the top level, even though i had the calculated value, the calculation is probably not correct, looks like there is a gap/offset between the image and the overlay causing the coordinates of the annotation to be negative in a small percentage of the viewer's (top). 

Any guess? not sure if I was clear enough explaining my approach, feel free to ask me to share better examples / more context.
