### ISSUE TITLE
Examples do not run properly with local built version due to random css issue

### ISSUE THREAD

**Issue by swederik** [MGHComputationalPathology/dicom-microscopy-viewer#46]
It appears that the viewer does not show up when you run the examples. It turns out that it is because the root element has no height or width and so it never gets displayed.

Not sure when this broke. We can just change it to `<div id="root" style="height:1000px; width:1000px"></div>` and it works fine.

Making an issue for anyone else that runs into it

**Comment by Punzo** [comment]
this has been solved in the current version

**Comment by hackermd** [comment]
> this has been solved in the current master, @hackermd you may close this

Great! Thanks @Punzo. Do you know the commit id or the number of the PR that resolved the issue? It would be great to link it here for future reference.

**Comment by Punzo** [comment]
> > this has been solved in the current master, @hackermd you may close this
> 
> Great! Thanks @Punzo. Do you know the commit id or the number of the PR that resolved the issue? It would be great to link it here for future reference.

ok, I agree in general. But if I remember well, I just add the small fix in the gigantic commit about multichannel API (i.e. https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/commit/7d22998194ee0f76952ba831c9035da85d964b76), which does not help in looking at the solution.

Anyway the solution was simply to add the pixel dimensions as suggested by Erik in https://github.com/MGHComputationalPathology/dicom-microscopy-viewer/issues/46#issue-802086785
