### ISSUE TITLE
Wrong markup measurements

### ISSUE THREAD

**Issue by hackermd** [MGHComputationalPathology/dicom-microscopy-viewer#51]
@igoroctaviano the markup measurements still seem to be off by quite a bit.

![Screen Shot 2021-05-12 at 4 21 27 PM](https://user-images.githubusercontent.com/6855297/118039309-30065e00-b33e-11eb-8d6d-41b67711d9f6.png)

**Comment by igoroctaviano** [comment]
> @igoroctaviano the markup measurements still seem to be off by quite a bit.
> 
> ![Screen Shot 2021-05-12 at 4 21 27 PM](https://user-images.githubusercontent.com/6855297/118039309-30065e00-b33e-11eb-8d6d-41b67711d9f6.png)

@hackermd can you describe the problem? what exactly is off?

**Comment by hackermd** [comment]
The scale bar in the lower right shows "200 µm", while the length measurement is "0.98 µm". The intestinal glands depicted in the image have a diameter of approximately 50 µm.

**Comment by igoroctaviano** [comment]
> The scale bar in the lower right shows "200 µm", while the length measurement is "0.98 µm". The intestinal glands depicted in the image have a diameter of approximately 50 µm.

I think that's probably because before I was calculating length and area from the feature directly and now it's being calculated after converting coordinates from feature to scoord. I'll take a look.
